<?php
return [

	/*
	|--------------------------------------------------------------------------
	| Message for all type of operation on system
	|--------------------------------------------------------------------------
	*/
	'admin-user' => [
		'invalid-credentials' => 'Please enter valid email and password',
		'success-login' => 'You are successfully logged in.',
		'success-logout' => 'You are successfully logged out.',
		'add-success' => 'Admin user added successfully.',
		'add-error' => 'Admin user not added successfully.',
		'update-success' => 'Admin user updated successfully.',
		'update-error' => 'Admin user not updated successfully.',
		'delete-success' => 'Admin user deleted successfully.',
		'password-success' => 'Admin user password changed successfully.',
		'password-error' => 'Admin user password not changed successfully.',
	],
	'reset-password' => [
		'invalid-credentials' => "Sorry, this email address is not registered with What's the Word? so there is no password to recover.",
		'success-mail' => 'Password reset link is sent to your email address.',
		'password-set' => 'Password reset successfully.',
		'reset-password-error' => 'Your email is invalid',
		'inactive-user' => 'Your account is de-activated',
	],
	'product' => [
		'add-success' => 'Product added successfully.',
		'add-error' => 'Product not added successfully.',
		'update-success' => 'Product updated successfully.',
		'update-error' => 'Product not updated successfully.',
		'delete-success' => 'Product deleted successfully.',
		'delete-error' => 'Product not deleted successfully.',
		'create-watermark-images' => 'Watermark images created successfully.',
		'create-watermark-thumb-images' => 'Watermark thumbnail images created successfully.',
		'create-thumb-images' => 'Thumb images created successfully.',
	],
	'orders' => [
		'add-success' => 'Order status updated successfully.',
	],
	'image' => [
		'add-success' => 'Image added successfully.',
		'image-required' => 'Please select image.',
	],
	'configuration' => [
		'add-success' => 'Configuration saved successfully.',
	],
	'notice' => [
		'pricing' => 'CSV file need to contains No of Letters,Frame Price, Unframe Price and Letters Only. And never include "$" with Price. ',
		'shipping-tax' => 'CSV file need to contains State Id and Tax Rate. And never include "%" with Tax Rate. ',
		'product-images' => 'CSV file need to contains Alphabet,Product Code and Image Name. ',
		'Frame' => 'CSV file need to contains Letter,Frame Type,Framed Size,Framed Grid. ',
		'shipping-cost' => 'CSV file need to contains Frame Id,No of frames,Shipping Method Id,Shipping Rate,State Id.And never include "$" with Shipping Rate. ',
		'delivery-time' => 'CSV file need to contains Frame Id,No of frames,Shipping Method Id,Minimum Delivery Time,Maximum Delivery Time,State Id. ',
	],
	'brand' => [
		'add-success' => 'Brand added successfully.',
		'add-error' => 'Please select alphabet letter or image.',
		'update-success' => 'Brand updated successfully.',
		'update-error' => 'Brand not updated successfully.',
		'delete-success' => 'Brand deleted successfully.',
		'delete-error' => 'Brand not deleted successfully.',
	],
	'promotion' => [
		'add-success' => 'Promotion added successfully.',
		'add-error' => 'Something went wrong, please try again later!',
		'update-success' => 'Promotion updated successfully.',
		'update-error' => 'Promotion not updated successfully.',
		'delete-success' => 'Promotion deleted successfully.',
		'delete-error' => 'Promotion not deleted successfully.',
	],
	'coupon-code' => [
		'add-success' => 'Coupon code added successfully.',
		'add-error' => 'Something went wrong, please try again later!',
		'update-success' => 'Coupon code updated successfully.',
		'update-error' => 'Coupon code not updated successfully.',
		'delete-success' => 'Coupon code deleted successfully.',
		'delete-error' => 'Coupon code not deleted successfully.',
	],
	'user' => [
		'invalid-credentials' => 'Please enter valid email and password',
		'success-login' => 'You are successfully logged in.',
		'success-register' => 'You are successfully registered. Check your email to confirm that you are registered.',
		'error-register' => 'Hmm, looks like you are already a customer of our website. Please try again by signing in or request a new password.',
		'success-logout' => 'You are successfully logged out.',
		'password-success' => 'Your password changed successfully.',
		'password-error' => 'Your password not changed successfully.',
	],
	'account' => [
		'password-success' => 'Your password changed successfully.',
		'password-error' => 'Your old password is incorrect.',
		'account-success' => 'Your information updated successfully.',
		'account-error' => 'Your information not updated successfully.',
		'delete-success' => 'Your address deleted successfully.',

	],
	'contact' => [
		'contact-success' => "Your message sent successfully.",
		'contact-error' => "Your message not sent successfully.",
	],
	'attribute' => [
		'add-success' => 'Attribute added successfully.',
		'add-error' => 'Attribute not added successfully.',
		'update-success' => 'Attribute updated successfully.',
		'update-error' => 'Attribute not updated successfully.',
		'delete-success' => 'Attribute deleted successfully.',
		'delete-error' => 'Attribute not deleted successfully.',
	],
	'attribute-set' => [
		'add-success' => 'Attribute Set added successfully.',
		'add-error' => 'Attribute Set not added successfully.',
		'update-success' => 'Attribute Set updated successfully.',
		'update-error' => 'Attribute Set not updated successfully.',
		'delete-success' => 'Attribute Set deleted successfully.',
		'delete-error' => 'Attribute Set not deleted successfully.',
	],
	'category' => [
		'add-success' => 'Category added successfully.',
		'add-error' => 'Category not added successfully.',
		'update-success' => 'Category updated successfully.',
		'update-error' => 'Category not updated successfully.',
		'delete-success' => 'Category deleted successfully.',
		'delete-error' => 'Category not deleted successfully.',
	],
	'role' => [
		'add-success' => 'Role added successfully.',
		'add-error' => 'Role not added successfully.',
		'update-success' => 'Role  updated successfully.',
		'update-error' => 'Role not updated successfully.',
		'delete-success' => 'Role deleted successfully.',
		'delete-error' => 'Role not deleted successfully.',
	],
	'page' => [
		'add-success' => 'Page added successfully.',
		'add-error' => 'Page not added successfully.',
		'update-success' => 'Page updated successfully.',
		'update-error' => 'Page not updated successfully.',
		'delete-success' => 'Page deleted successfully.',
		'delete-error' => 'Page not deleted successfully.',
	],
	'admin' => [
		'add-success' => 'Admin User added successfully.',
		'add-error' => 'Admin User not added successfully.',
		'update-success' => 'Admin User updated successfully.',
		'update-error' => 'Admin User not updated successfully.',
		'delete-success' => 'Admin User deleted successfully.',
		'delete-error' => 'Admin User not deleted successfully.',
	],
	'email-template' => [
		'add-success' => 'Email Template added successfully.',
		'add-error' => 'Email Template not added successfully.',
		'update-success' => 'Email Template updated successfully.',
		'update-error' => 'Email Template not updated successfully.',
		'delete-success' => 'Email Template deleted successfully.',
		'delete-error' => 'Email Template not deleted successfully.',
	],
	'banner' => [
		'add-success' => 'Banner added successfully.',
		'add-error' => 'Banner not added successfully.',
		'update-success' => 'Banner updated successfully.',
		'update-error' => 'Banner not updated successfully.',
		'delete-success' => 'Banner deleted successfully.',
		'delete-error' => 'Banner not deleted successfully.',
	],
	'rating' => [
		'update-success' => 'Rating updated successfully.',
		'update-error' => 'Rating not updated successfully.',
		'delete-success' => 'Rating deleted successfully.',
		'delete-error' => 'Rating not deleted successfully.',
	],
	'order-status' => [
		'add-success' => 'Order Status added successfully.',
		'add-error' => 'Order Status not added successfully.',
		'update-success' => 'Order Status updated successfully.',
		'update-error' => 'Order Status not updated successfully.',
		'delete-success' => 'Order Status deleted successfully.',
		'delete-error' => 'Order Status not deleted successfully.',
	],
	'store' => [
		'add-success' => 'Store added successfully.',
		'add-error' => 'Store not added successfully.',
		'update-success' => 'Store updated successfully.',
		'update-error' => 'Store not updated successfully.',
		'delete-success' => 'Store deleted successfully.',
		'delete-error' => 'Store not deleted successfully.',
	],
    'link_adjustment' => [
        'add-success' => 'Link added successfully.',
        'add-error' => 'Link not added successfully.',
        'update-success' => 'Link updated successfully.',
        'update-error' => 'Link not updated successfully.',
        'delete-success' => 'Link deleted successfully.',
        'delete-error' => 'Link not deleted successfully.',
    ],
    'special-product' => [
        'add-success' => 'Special Product added successfully.',
        'add-error' => 'Special Product not added successfully.',
        'update-success' => 'Special Product updated successfully.',
        'update-error' => 'Special Product not updated successfully.',
        'delete-success' => 'Special Product deleted successfully.',
        'delete-error' => 'Special Product not deleted successfully.',
    ],
	'blog-category'=>[
		'add-success' => 'Blog Category added successfully.',
		'add-error' => 'Blog Category not added successfully.',
		'update-success' => 'Blog Category updated successfully.',
		'update-error' => 'Blog Category not updated successfully.',
		'delete-success' => 'Blog Category deleted successfully.',
		'delete-error' => 'Blog Category not deleted successfully.',
	],
	'blog-post'=>[
		'add-success' => 'Blog Post added successfully.',
		'add-error' => 'Blog Post not added successfully.',
		'update-success' => 'Blog Post updated successfully.',
		'update-error' => 'Blog Post not updated successfully.',
		'delete-success' => 'Blog Post deleted successfully.',
		'delete-error' => 'Blog Post not deleted successfully.',
	],
	'order'=>[
		'delete-success'=>"Order deleted successfully.",
		'update-success'=>"Order status updated successfully."
	],
	'faq'=>[
		'add-success' => 'FAQ added successfully.',
		'add-error' => 'FAQ not added successfully.',
		'update-success' => 'FAQ updated successfully.',
		'update-error' => 'FAQ not updated successfully.',
		'delete-success' => 'FAQ deleted successfully.',
		'delete-error' => 'FAQ not deleted successfully.',
	],
	'epartner'=>[
		'add-success' => 'Epartner Media added successfully.',
		'add-error' => 'Epartner Media not added successfully.',
		'update-success' => 'Epartner Media updated successfully.',
		'update-error' => 'Epartner Media not updated successfully.',
		'delete-success' => 'Epartner Media deleted successfully.',
		'delete-error' => 'Epartner Media not deleted successfully.',
	],
	'invoice'=>[
		'add-success' => 'Invoice added successfully.',
		'add-error' => 'Invoice not added successfully.',
		'update-success' => 'Invoice updated successfully.',
		'update-error' => 'Invoice not updated successfully.',
		'delete-success' => 'Invoice deleted successfully.',
		'delete-error' => 'Invoice not deleted successfully.',
	],



];

